In [1]:
import torch

In [3]:
model = torch.nn.Linear(3, 1)

torch.nn.init.uniform_(model.weight)
# this method can suffer from the ‘exploding gradient’ problem if the range is too large.

Parameter containing:
tensor([[0.8680, 0.4172, 0.0525]], requires_grad=True)

In [4]:
torch.nn.init.xavier_uniform_(model.weight)
# Xavier initialization can help prevent the ‘vanishing gradient’ problem, as it scales the weights such that the variance of the outputs of each layer is the same as the variance of the inputs.

Parameter containing:
tensor([[-0.1889,  0.0459, -0.8971]], requires_grad=True)

In [5]:
torch.nn.init.kaiming_uniform_(model.weight,
                               a=0, mode='fan_in',
                               nonlinearity='relu')
# Kaiming initialization can help prevent the ‘vanishing gradient’ problem, as it scales the weights such that the variance of the outputs is the same as the variance of the inputs, taking into account the nonlinearity of the activation function.

Parameter containing:
tensor([[ 0.1988, -0.8268, -1.1556]], requires_grad=True)

In [6]:
torch.nn.init.zeros_(model.weight)
#  weights to zeros can cause the model to converge slowly, as all of the weights will be updated in the same direction. This can also lead to the ‘vanishing gradient’ problem

Parameter containing:
tensor([[0., 0., 0.]], requires_grad=True)

In [9]:
torch.nn.init.ones_(model.weight)
# e weights to ones can cause the model to converge slowly, as all of the weights will be updated in the same direction. This can also lead to the ‘exploding gradient’ problem. 

Parameter containing:
tensor([[1., 1., 1.]], requires_grad=True)

In [10]:
torch.nn.init.normal_(model.weight)
 # a normal distribution to initialize the weights can help prevent the ‘exploding gradient’ problem, as the distribution has a finite range and the weights are distributed evenly around the mean

Parameter containing:
tensor([[-1.9404, -1.8768, -1.0449]], requires_grad=True)